use_frameworks!

target 'BJTransition_Example' do
  pod 'BJTransition', :path => '../'

  target 'BJTransition_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
